version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper@sha256:6dfdaae24f3d1ef77e76dff85a5ab8ac7edb2d145935f213b7ae5176377eacc1
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui@sha256:9659927f707a97d6c6349bcda005520c9041d49f162a2124268368d88e289a19
    ports:
      - "9090:9090"
  broker:
    image: qnib/plain-kafka:0.10.2.1@sha256:c0cb9ad254228b2186b3d6607cce4df08c461e318111b3c114cf8e16105892df
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: '{{.Task.Slot}}'
  manager:
    image: qnib/plain-kafka-manager:1.3.3.14
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_HOSTS: "tasks.zookeeper:2181"
  engine:
    image: qnib/plain-ksql:dirty
    environment:
      KAFKA_BROKERS: "tasks.broker:9092"
